### ISSUE TITLE
passing an extra parameters to getters

### ISSUE THREAD

**Issue by moh586** [andrewvasilchuk/vuex-typescript#2]
I want to pass an extra parameter to getters. 

For example:
`doubledCounter(state: State, value: number): number`

When I use this style I get an error that says `doubledCounter` is not a function.

**Comment by moh586** [comment]
I found the solution.

```ts
export type Getters = {
  doubledCounter(state: State): (value: number) => number
}

export const getters: GetterTree<State, State> & Getters = {
  doubledCounter: (state) => {
     return (value: number) => {
       return state.counter * value;
     }
  },
}
```

Now in `.vue` file just use `doubledCounter(value)`  like `doubledCounter(5)`.

**Comment by andrewvasilchuk** [comment]
@moh586 glad you found the solution :)
